apiVersion: v1
kind: Service
metadata:
  name: hook-runner-service
spec:
  selector:
    app: hook-runner
  ports:
    - protocol: TCP
      port: 8081  # The port you want to expose on the service
      targetPort: 8081  # The port your microservice listens on in the container
  type: LoadBalancer  # Use NodePort or ClusterIP as needed
